apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-batch-config
  namespace: bigdata
  labels:
    app: spark-batch
data:
  HDFS_OUTPUT_PATH: "hdfs://hdfs-namenode.bigdata.svc.cluster.local:8020/weather-data"
  MONGODB_URI: "mongodb://mongodb.bigdata.svc.cluster.local:27017/weather_db"
