apiVersion: v1
kind: Secret # loại tài nguyên là secret
metadata:
  name: spark-consumer-secrets # tên của secret
  namespace: bigdata # cụm namespace
  labels: #labels cho secret
    app: spark-streaming-consumer
type: Opaque
stringData: #dữ liệu của secret ở dạng chuỗi
  INFLUXDB_TOKEN: "wCXJQbt3yjykKYrnVxSrjkXFnQ0fv0p2UIer4Z8j0bOkKfPId_3n_LgZa-5TQ9ElOI8TWQ7GFrf0xFCWcRPkCg=="
